//
//  HotelReservationsStyleKit.h
//  HotelReservations
//
//  Created by jnagel on 5/6/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface HotelReservationsStyleKit : NSObject

// Colors
+ (UIColor*)darkYellow;
+ (UIColor*)blueDark;
+ (UIColor*)blueLight;

// Gradients
+ (PCGradient*)gradient2;

// Drawing Methods
+ (void)drawSectionHeaderWithFrame: (CGRect)frame;
+ (void)drawPlusButtonWithFrame: (CGRect)frame;
+ (void)drawMinusButtonWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfSectionHeaderWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPlusButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfMinusButtonWithFrame: (CGRect)frame;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
