//
//  HotelReservationsStyleKit.m
//  HotelReservations
//
//  Created by jnagel on 5/5/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "HotelReservationsStyleKit.h"


@implementation HotelReservationsStyleKit

#pragma mark Cache

static UIColor* _gradientColor = nil;
static UIColor* _gradientColor2 = nil;

#pragma mark Initialization

+ (void)initialize
{
    _gradientColor = [UIColor colorWithRed: 0.523 green: 0.739 blue: 0.344 alpha: 1];
    _gradientColor2 = [UIColor colorWithRed: 0.145 green: 0.321 blue: 0.058 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)gradientColor { return _gradientColor; }
+ (UIColor*)gradientColor2 { return _gradientColor2; }

#pragma mark Drawing Methods

+ (void)drawSectionHeaderWithFrame: (CGRect)frame
{
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    CGFloat gradientLocations[] = {0, 1};
    CGGradientRef gradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)HotelReservationsStyleKit.gradientColor.CGColor, (id)HotelReservationsStyleKit.gradientColor2.CGColor], gradientLocations);

    CGRect rectangleRect = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame), CGRectGetWidth(frame), CGRectGetHeight(frame));
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: rectangleRect];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGFloat rectangleResizeRatio = MIN(CGRectGetWidth(rectangleRect) / 600, CGRectGetHeight(rectangleRect) / 40);
    CGContextDrawRadialGradient(context, gradient,
        CGPointMake(CGRectGetMidX(rectangleRect) + -16.81 * rectangleResizeRatio, CGRectGetMidY(rectangleRect) + 1.09 * rectangleResizeRatio), 22.7 * rectangleResizeRatio,
        CGPointMake(CGRectGetMidX(rectangleRect) + -19.45 * rectangleResizeRatio, CGRectGetMidY(rectangleRect) + 1.44 * rectangleResizeRatio), 466.5 * rectangleResizeRatio,
        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGContextRestoreGState(context);

    CGGradientRelease(gradient);
    CGColorSpaceRelease(colorSpace);
}

#pragma mark Generated Images

+ (UIImage*)imageOfSectionHeaderWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [HotelReservationsStyleKit drawSectionHeaderWithFrame: frame];

    UIImage* imageOfSectionHeader = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfSectionHeader;
}

@end
