//
//  HotelReservationsStyleKit.h
//  HotelReservations
//
//  Created by jnagel on 5/5/15.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface HotelReservationsStyleKit : NSObject

// Drawing Methods
+ (void)drawSectionHeaderWithFrame: (CGRect)frame;

@end
